import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Breadcrumbs from "@/components/Breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={inter.className}>
        <header>
          <h1 className="text-2xl font-bold font-bold text-center mt-4 mb-2">My Application</h1>
          <Breadcrumbs />
        </header>
        <main className="">
          {children}
        </main>
      </body>
      {/* <body >{children}</body> */}
    </html>
  );
}
